<!DOCTYPE html><html lang=pt-BR class=contrast><head><script>(function(w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
        var f = d.getElementsByTagName(s)[0],
          j = d.createElement(s),
          dl = l != "dataLayer" ? "&l=" + l : "";
        j.async = true;
        j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
        f.parentNode.insertBefore(j, f);
      })(window, document, "script", "dataLayer", "GTM-5LK9RB4");</script><meta charset=utf-8><meta name=description content="Soluções personalizadas e oportunidades de negócios para o seu perfil."><meta name=keywords content="Empreendedorismo, oportunidades, negócios, empreendedor, Soluções, Cursos"><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=apple-touch-icon sizes=57x57 href=favicon/apple-icon-57x57.png><link rel=apple-touch-icon sizes=60x60 href=favicon/apple-icon-60x60.png><link rel=apple-touch-icon sizes=72x72 href=favicon/apple-icon-72x72.png><link rel=apple-touch-icon sizes=76x76 href=favicon/apple-icon-76x76.png><link rel=apple-touch-icon sizes=114x114 href=favicon/apple-icon-114x114.png><link rel=apple-touch-icon sizes=120x120 href=favicon/apple-icon-120x120.png><link rel=apple-touch-icon sizes=144x144 href=favicon/apple-icon-144x144.png><link rel=apple-touch-icon sizes=152x152 href=favicon/apple-icon-152x152.png><link rel=apple-touch-icon sizes=180x180 href=favicon/apple-icon-180x180.png><link rel=icon type=image/png sizes=192x192 href=favicon/android-icon-192x192.png><link rel=icon type=image/png sizes=32x32 href=favicon/favicon-32x32.png><link rel=icon type=image/png sizes=96x96 href=favicon/favicon-96x96.png><link rel=icon type=image/png sizes=16x16 href=favicon/favicon-16x16.png><link rel=manifest href=favicon/manifest.json><meta name=msapplication-TileColor content=#ffffff><meta name=msapplication-TileImage content=/ms-icon-144x144.png><meta name=theme-color content=#ffffff><title>Sebrae números</title><link href=css/app.7b0b49a9.css rel=preload as=style><link href=css/chunk-vendors.d6d55b4a.css rel=preload as=style><link href=js/app.f9d99fe6.js rel=preload as=script><link href=js/chunk-vendors.6bceb63a.js rel=preload as=script><link href=css/chunk-vendors.d6d55b4a.css rel=stylesheet><link href=css/app.7b0b49a9.css rel=stylesheet></head><body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5LK9RB4" height=0 width=0 style=display:none;visibility:hidden></iframe></noscript><noscript><strong>Lamentamos, mas nosso site não funciona corretamente sem o JavaScript ativado. Ative-o para continuar.</strong></noscript><div id=app></div><script src=js/chunk-vendors.6bceb63a.js></script><script src=js/app.f9d99fe6.js></script></body></html>